#! /usr/bin/env bash
set -eu

pidfile=/var/run/asterisk/asterisk.pid
command=/usr/sbin/fwconsole

# Proxy signals
function kill_app(){
    #kill $(cat $pidfile)
    $command stop
    exit $?
}
trap "kill_app" SIGINT SIGTERM

# configure permissions before starting
#$command chown

# start asterisk
$command start -q
sleep 2

# Loop while the pidfile and the process exist
while [ -f $pidfile ] && kill -0 $(cat $pidfile) ; do
    sleep 5
done
exit 1000 # exit unexpected
