#!/bin/sh
# script to renew let's encrypt certificates using freepbx fwconsole command

if [ "$LETSENCRYPT_ENABLED" == "true" ]; then
  fwconsole certificates --updateall -q
  [ $? -eq 0 ] && supervisorctl restart httpd 1>/dev/null 
fi
